table 'Category Results'
	lineageTag: e4cda6b9-acfc-5d14-b142-1ed5ee5e12f2

	column method
		dataType: string
		lineageTag: bb69afc6-1d82-5d24-9c23-7e6ecd640ddc
		summarizeBy: none
		sourceColumn: method

		annotation SummarizationSetBy = User

	column category
		dataType: string
		lineageTag: 5cdbf618-fb93-514b-849c-2f48d0c57930
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = User

	column anomaly_type
		dataType: string
		lineageTag: c8225a47-5abe-5f66-aa74-7b32ed800467
		summarizeBy: none
		sourceColumn: anomaly_type

		annotation SummarizationSetBy = User

	column n_good
		dataType: int64
		formatString: #,0
		lineageTag: 3154b8b5-cfb4-59c6-80e8-fb7d910e89cf
		summarizeBy: none
		sourceColumn: n_good

		annotation SummarizationSetBy = User

	column n_anomaly
		dataType: int64
		formatString: #,0
		lineageTag: 3a24ae64-fbc0-5ee5-8d99-463e1849151b
		summarizeBy: none
		sourceColumn: n_anomaly

		annotation SummarizationSetBy = User

	column auroc
		dataType: double
		formatString: 0.000
		lineageTag: 46ccc6c2-65ee-5e6f-9f58-6662a6f1612e
		summarizeBy: none
		sourceColumn: auroc

		annotation SummarizationSetBy = User

	column f1
		dataType: double
		formatString: 0.000
		lineageTag: 5821d59d-dfc2-5d11-8255-5a14ec37569a
		summarizeBy: none
		sourceColumn: f1

		annotation SummarizationSetBy = User

	column precision
		dataType: double
		formatString: 0.000
		lineageTag: bfd08758-6460-5304-a3df-f0ae48257fac
		summarizeBy: none
		sourceColumn: precision

		annotation SummarizationSetBy = User

	column recall
		dataType: double
		formatString: 0.000
		lineageTag: fef52f69-b307-5728-ab40-cd9506ca0cc9
		summarizeBy: none
		sourceColumn: recall

		annotation SummarizationSetBy = User

	column val_threshold
		dataType: double
		formatString: 0.000
		lineageTag: 6abfc1cf-1a3d-5e9a-aa69-f58b87b3a756
		summarizeBy: none
		sourceColumn: val_threshold

		annotation SummarizationSetBy = User

	partition 'Category Results-Embedded' = m
		mode: import
		source =
				let
				    Source = Csv.Document(Binary.FromText("bWV0aG9kLGNhdGVnb3J5LGFub21hbHlfdHlwZSxuX2dvb2Qsbl9hbm9tYWx5LGF1cm9jLGYxLHByZWNpc2lvbixyZWNhbGwsdmFsX3RocmVzaG9sZApHbG9iYWwgSW1hZ2UtU3RhdCBEZXRlY3RvciAocHJveHkpLGJyZWFrZmFzdF9ib3gsbG9naWNhbCwxMDIsODMsMC44NjY4NzkyODE4MzMyMTUzLDAuNzEyMTIxMjEyMTIxMjEyMiwwLjk1OTE4MzY3MzQ2OTM4NzcsMC41NjYyNjUwNjAyNDA5NjM5LDEuNTU4MTUwODk5NDEwMjQ3NQpHbG9iYWwgSW1hZ2UtU3RhdCBEZXRlY3RvciAocHJveHkpLGJyZWFrZmFzdF9ib3gsc3RydWN0dXJhbCwxMDIsOTAsMC42MTU5MDQxMzk0MzM1NTEzLDAuMzQyMzQyMzQyMzQyMzQyMzQsMC45MDQ3NjE5MDQ3NjE5MDQ4LDAuMjExMTExMTExMTExMTExMSwxLjU1ODE1MDg5OTQxMDI0NzUKR2xvYmFsIEltYWdlLVN0YXQgRGV0ZWN0b3IgKHByb3h5KSxicmVha2Zhc3RfYm94LG92ZXJhbGwsMTAyLDE3MywwLjczNjMxNDE3ODg1MDczMSwwLjU0NzcxNzg0MjMyMzY1MTUsMC45NzA1ODgyMzUyOTQxMTc2LDAuMzgxNTAyODkwMTczNDEwNCwxLjU1ODE1MDg5OTQxMDI0NzUKR2xvYmFsIEltYWdlLVN0YXQgRGV0ZWN0b3IgKHByb3h5KSxqdWljZV9ib3R0bGUsbG9naWNhbCw5NCwxNDIsMC43MTQ2Mzg4OTcyMTMwNjU2LDAuNjM4Mjk3ODcyMzQwNDI1NiwwLjgwNjQ1MTYxMjkwMzIyNTgsMC41MjgxNjkwMTQwODQ1MDcsMS4xNTI4MzIzNTMxMTUwODE3Ckdsb2JhbCBJbWFnZS1TdGF0IERldGVjdG9yIChwcm94eSksanVpY2VfYm90dGxlLHN0cnVjdHVyYWwsOTQsOTQsMC41NjU5ODAwODE0ODQ4MzQ3LDAuMzUyOTQxMTc2NDcwNTg4MjYsMC41NzE0Mjg1NzE0Mjg1NzE0LDAuMjU1MzE5MTQ4OTM2MTcwMiwxLjE1MjgzMjM1MzExNTA4MTcKR2xvYmFsIEltYWdlLVN0YXQgRGV0ZWN0b3IgKHByb3h5KSxqdWljZV9ib3R0bGUsb3ZlcmFsbCw5NCwyMzYsMC42NTU0MjczMzUwMTYyMjc5LDAuNTYwOTA2NTE1NTgwNzM2NiwwLjg0NjE1Mzg0NjE1Mzg0NjEsMC40MTk0OTE1MjU0MjM3Mjg4LDEuMTUyODMyMzUzMTE1MDgxNwpHbG9iYWwgSW1hZ2UtU3RhdCBEZXRlY3RvciAocHJveHkpLHB1c2hwaW5zLGxvZ2ljYWwsMTM4LDkxLDAuNTYwNzU4MDgyNDk3MjEyOSwwLjU5NDc5NTUzOTAzMzQ1NzMsMC40NDk0MzgyMDIyNDcxOTEsMC44NzkxMjA4NzkxMjA4NzkxLDEuMzQ0MzE0NzY1OTMwMTc1NwpHbG9iYWwgSW1hZ2UtU3RhdCBEZXRlY3RvciAocHJveHkpLHB1c2hwaW5zLHN0cnVjdHVyYWwsMTM4LDgxLDAuOTg5MzU0MDg4Mzg3OTA0NywwLjYyMzA3NjkyMzA3NjkyMzEsMC40NTI1MTM5NjY0ODA0NDY5NSwxLjAsMS4zNDQzMTQ3NjU5MzAxNzU3Ckdsb2JhbCBJbWFnZS1TdGF0IERldGVjdG9yIChwcm94eSkscHVzaHBpbnMsb3ZlcmFsbCwxMzgsMTcyLDAuNzYyNTk2ODk5MjI0ODA2MiwwLjc0NzA5OTc2Nzk4MTQzODUsMC42MjE2MjE2MjE2MjE2MjE2LDAuOTM2MDQ2NTExNjI3OTA3LDEuMzQ0MzE0NzY1OTMwMTc1NwpHbG9iYWwgSW1hZ2UtU3RhdCBEZXRlY3RvciAocHJveHkpLHNjcmV3X2JhZyxsb2dpY2FsLDEyMiwxMzcsMC42NzIzMTA2Mzc3ODg2ODAyLDAuMjAzODIxNjU2MDUwOTU1NDIsMC44LDAuMTE2Nzg4MzIxMTY3ODgzMjEsMS4zODAyODk1NjY1MTY4NzYKR2xvYmFsIEltYWdlLVN0YXQgRGV0ZWN0b3IgKHByb3h5KSxzY3Jld19iYWcsc3RydWN0dXJhbCwxMjIsODIsMC43MzE2MDczNTcwNTcxNzcsMC40MDc0MDc0MDc0MDc0MDc0LDAuODQ2MTUzODQ2MTUzODQ2MSwwLjI2ODI5MjY4MjkyNjgyOTMsMS4zODAyODk1NjY1MTY4NzYKR2xvYmFsIEltYWdlLVN0YXQgRGV0ZWN0b3IgKHByb3h5KSxzY3Jld19iYWcsb3ZlcmFsbCwxMjIsMjE5LDAuNjk0NTEzMDYyMzU0OTY2NywwLjI5MTE4NzczOTQ2MzYwMTU1LDAuOTA0NzYxOTA0NzYxOTA0OCwwLjE3MzUxNTk4MTczNTE1OTgsMS4zODAyODk1NjY1MTY4NzYKR2xvYmFsIEltYWdlLVN0YXQgRGV0ZWN0b3IgKHByb3h5KSxzcGxpY2luZ19jb25uZWN0b3JzLGxvZ2ljYWwsMTE5LDEwOCwwLjM1NjA1MzUzMjUyNDEyMDc1LDAuMTM3NDA0NTgwMTUyNjcxNzYsMC4zOTEzMDQzNDc4MjYwODcsMC4wODMzMzMzMzMzMzMzMzMzMywxLjI2NjQxNzcxNzkzMzY1NDcKR2xvYmFsIEltYWdlLVN0YXQgRGV0ZWN0b3IgKHByb3h5KSxzcGxpY2luZ19jb25uZWN0b3JzLHN0cnVjdHVyYWwsMTE5LDg1LDAuNTEzMzk1OTQ2NjEzOTM5NywwLjI5MzEwMzQ0ODI3NTg2MjA0LDAuNTQ4Mzg3MDk2Nzc0MTkzNSwwLjIsMS4yNjY0MTc3MTc5MzM2NTQ3Ckdsb2JhbCBJbWFnZS1TdGF0IERldGVjdG9yIChwcm94eSksc3BsaWNpbmdfY29ubmVjdG9ycyxvdmVyYWxsLDExOSwxOTMsMC40MjUzNDk0MTQzNzcxNDk4LDAuMjIzMTc1OTY1NjY1MjM2MDYsMC42NSwwLjEzNDcxNTAyNTkwNjczNTc2LDEuMjY2NDE3NzE3OTMzNjU0NwpESU5PdjIgUGF0Y2ggTWVtb3J5IChOTiksYnJlYWtmYXN0X2JveCxsb2dpY2FsLDEwMiw4MywwLjc5MTE2NDY1ODYzNDUzODEsMC42MzE1Nzg5NDczNjg0MjEsMC44NCwwLjUwNjAyNDA5NjM4NTU0MjEsMC41Nzk3NzU2Mzc4NDY3MjY3CkRJTk92MiBQYXRjaCBNZW1vcnkgKE5OKSxicmVha2Zhc3RfYm94LHN0cnVjdHVyYWwsMTAyLDkwLDAuODA4OTMyNDYxODczNjM4MiwwLjY0ODI3NTg2MjA2ODk2NTUsMC44NTQ1NDU0NTQ1NDU0NTQ1LDAuNTIyMjIyMjIyMjIyMjIyMywwLjU3OTc3NTYzNzg0NjcyNjcKRElOT3YyIFBhdGNoIE1lbW9yeSAoTk4pLGJyZWFrZmFzdF9ib3gsb3ZlcmFsbCwxMDIsMTczLDAuODAwNDA4MDI0NDgxNDY4OSwwLjY1OTI1OTI1OTI1OTI1OTIsMC45MTc1MjU3NzMxOTU4NzYyLDAuNTE0NDUwODY3MDUyMDIzMSwwLjU3OTc3NTYzNzg0NjcyNjcKRElOT3YyIFBhdGNoIE1lbW9yeSAoTk4pLGp1aWNlX2JvdHRsZSxsb2dpY2FsLDk0LDE0MiwwLjg5MjcxODAxMDE4ODc5MjQsMC44MjE3MDU0MjYzNTY1ODkyLDAuOTEzNzkzMTAzNDQ4Mjc1OSwwLjc0NjQ3ODg3MzIzOTQzNjYsMC4zNzk0ODQxNzU3MTg3NDc2CkRJTk92MiBQYXRjaCBNZW1vcnkgKE5OKSxqdWljZV9ib3R0bGUsc3RydWN0dXJhbCw5NCw5NCwwLjkyNTY0NTA4ODI3NTIzNzYsMC44MzE0NjA2NzQxNTczMDM0LDAuODgwOTUyMzgwOTUyMzgwOSwwLjc4NzIzNDA0MjU1MzE5MTUsMC4zNzk0ODQxNzU3MTg3NDc2CkRJTk92MiBQYXRjaCBNZW1vcnkgKE5OKSxqdWljZV9ib3R0bGUsb3ZlcmFsbCw5NCwyMzYsMC45MDU4MzMwMzI4MTY0NDQyLDAuODQ1MDcwNDIyNTM1MjExMywwLjk0NzM2ODQyMTA1MjYzMTUsMC43NjI3MTE4NjQ0MDY3Nzk2LDAuMzc5NDg0MTc1NzE4NzQ3NgpESU5PdjIgUGF0Y2ggTWVtb3J5IChOTikscHVzaHBpbnMsbG9naWNhbCwxMzgsOTEsMC40OTI1MTQ3MzE2NDUxNjY0LDAuNDA4ODM5Nzc5MDA1NTI0OSwwLjQxMTExMTExMTExMTExMTEsMC40MDY1OTM0MDY1OTM0MDY2LDAuNDYxODUwNTM4MTYyMDg0NwpESU5PdjIgUGF0Y2ggTWVtb3J5IChOTikscHVzaHBpbnMsc3RydWN0dXJhbCwxMzgsODEsMC41Nzk5Nzg1MjkyNTM4OTE2LDAuNDE0MjAxMTgzNDMxOTUyNjcsMC4zOTc3MjcyNzI3MjcyNzI3LDAuNDMyMDk4NzY1NDMyMDk4NzQsMC40NjE4NTA1MzgxNjIwODQ3CkRJTk92MiBQYXRjaCBNZW1vcnkgKE5OKSxwdXNocGlucyxvdmVyYWxsLDEzOCwxNzIsMC41MzM3MDQwNzgxOTM0NjE0LDAuNDg0ODQ4NDg0ODQ4NDg0ODYsMC41NzYsMC40MTg2MDQ2NTExNjI3OTA3LDAuNDYxODUwNTM4MTYyMDg0NwpESU5PdjIgUGF0Y2ggTWVtb3J5IChOTiksc2NyZXdfYmFnLGxvZ2ljYWwsMTIyLDEzNywwLjUyNDY0OTk5NDAxNjk5MTcsMC4xOTE2MTY3NjY0NjcwNjU4OCwwLjUzMzMzMzMzMzMzMzMzMzMsMC4xMTY3ODgzMjExNjc4ODMyMSwwLjYzMzMyMjQzNjA3NTk0NDIKRElOT3YyIFBhdGNoIE1lbW9yeSAoTk4pLHNjcmV3X2JhZyxzdHJ1Y3R1cmFsLDEyMiw4MiwwLjc4NTQ4NTgwNTY3NzcyODksMC41NDU0NTQ1NDU0NTQ1NDU0LDAuNzIsMC40MzkwMjQzOTAyNDM5MDI0NCwwLjYzMzMyMjQzNjA3NTk0NDIKRElOT3YyIFBhdGNoIE1lbW9yeSAoTk4pLHNjcmV3X2JhZyxvdmVyYWxsLDEyMiwyMTksMC42MjIzMTQ1NDQ1MDE4MzQsMC4zNjQ5MTIyODA3MDE3NTQ0LDAuNzg3ODc4Nzg3ODc4Nzg3OCwwLjIzNzQ0MjkyMjM3NDQyOTIsMC42MzMzMjI0MzYwNzU5NDQyCkRJTk92MiBQYXRjaCBNZW1vcnkgKE5OKSxzcGxpY2luZ19jb25uZWN0b3JzLGxvZ2ljYWwsMTE5LDEwOCwwLjc4NjQxNDU2NTgyNjMzMDYsMC42ODY1NjcxNjQxNzkxMDQ1LDAuNzQxOTM1NDgzODcwOTY3NywwLjYzODg4ODg4ODg4ODg4ODgsMC40ODMwNDY5NDc1MzQyNjc3CkRJTk92MiBQYXRjaCBNZW1vcnkgKE5OKSxzcGxpY2luZ19jb25uZWN0b3JzLHN0cnVjdHVyYWwsMTE5LDg1LDAuNzI1ODUyNjk0MDE4Nzg0LDAuNjIwMjUzMTY0NTU2OTYyLDAuNjcxMjMyODc2NzEyMzI4OCwwLjU3NjQ3MDU4ODIzNTI5NDEsMC40ODMwNDY5NDc1MzQyNjc3CkRJTk92MiBQYXRjaCBNZW1vcnkgKE5OKSxzcGxpY2luZ19jb25uZWN0b3JzLG92ZXJhbGwsMTE5LDE5MywwLjc1OTc0MjIzODg2NDQ1NzgsMC43MDQ0Nzc2MTE5NDAyOTg1LDAuODMwOTg1OTE1NDkyOTU3NywwLjYxMTM5ODk2MzczMDU2OTksMC40ODMwNDY5NDc1MzQyNjc3CkRJTk92MiBSZWdpb24tQXdhcmUgTWVtb3J5LGJyZWFrZmFzdF9ib3gsbG9naWNhbCwxMDIsODMsMC44NDE3MTk4MjA0NTgzMDM4LDAuNzE5NDI0NDYwNDMxNjU0NiwwLjg5Mjg1NzE0Mjg1NzE0MjksMC42MDI0MDk2Mzg1NTQyMTY5LDAuNTUzNzE1MjI0NDQ5NDUxMgpESU5PdjIgUmVnaW9uLUF3YXJlIE1lbW9yeSxicmVha2Zhc3RfYm94LHN0cnVjdHVyYWwsMTAyLDkwLDAuODE3MjExMzI4OTc2MDM0OSwwLjc0NTA5ODAzOTIxNTY4NjMsMC45MDQ3NjE5MDQ3NjE5MDQ4LDAuNjMzMzMzMzMzMzMzMzMzMywwLjU1MzcxNTIyNDQ0OTQ1MTIKRElOT3YyIFJlZ2lvbi1Bd2FyZSBNZW1vcnksYnJlYWtmYXN0X2JveCxvdmVyYWxsLDEwMiwxNzMsMC44Mjg5Njk3MzgxODQyOTExLDAuNzQ4MjUxNzQ4MjUxNzQ4MiwwLjk0NjkwMjY1NDg2NzI1NjcsMC42MTg0OTcxMDk4MjY1ODk2LDAuNTUzNzE1MjI0NDQ5NDUxMgpESU5PdjIgUmVnaW9uLUF3YXJlIE1lbW9yeSxqdWljZV9ib3R0bGUsbG9naWNhbCw5NCwxNDIsMC45MzYyNDUxMzAzNTY2MDc4LDAuODY0NDY4ODY0NDY4ODY0NSwwLjkwMDc2MzM1ODc3ODYyNTksMC44MzA5ODU5MTU0OTI5NTc3LDAuMzE0ODcxMzc4MTI4MzQ1MTUKRElOT3YyIFJlZ2lvbi1Bd2FyZSBNZW1vcnksanVpY2VfYm90dGxlLHN0cnVjdHVyYWwsOTQsOTQsMC45NTM5Mzg0MzM2ODAzOTgzLDAuODg1NDE2NjY2NjY2NjY2NiwwLjg2NzM0NjkzODc3NTUxMDIsMC45MDQyNTUzMTkxNDg5MzYyLDAuMzE0ODcxMzc4MTI4MzQ1MTUKRElOT3YyIFJlZ2lvbi1Bd2FyZSBNZW1vcnksanVpY2VfYm90dGxlLG92ZXJhbGwsOTQsMjM2LDAuOTQzMjkyNDYzMDM2NDIyNywwLjg5ODIzMDA4ODQ5NTU3NTIsMC45Mzk4MTQ4MTQ4MTQ4MTQ4LDAuODYwMTY5NDkxNTI1NDIzOCwwLjMxNDg3MTM3ODEyODM0NTE1CkRJTk92MiBSZWdpb24tQXdhcmUgTWVtb3J5LHB1c2hwaW5zLGxvZ2ljYWwsMTM4LDkxLDAuNTMzNjA0MDc3MDgyMzM3OSwwLjMxNzg4MDc5NDcwMTk4Njc3LDAuNCwwLjI2MzczNjI2MzczNjI2Mzc0LDAuNDM3NjI4NzM1NDg3Mjc3NwpESU5PdjIgUmVnaW9uLUF3YXJlIE1lbW9yeSxwdXNocGlucyxzdHJ1Y3R1cmFsLDEzOCw4MSwwLjYyMjc0MTA5ODU4NjUwOTIsMC40MDgxNjMyNjUzMDYxMjI0NiwwLjQ1NDU0NTQ1NDU0NTQ1NDUzLDAuMzcwMzcwMzcwMzcwMzcwMzUsMC40Mzc2Mjg3MzU0ODcyNzc3CkRJTk92MiBSZWdpb24tQXdhcmUgTWVtb3J5LHB1c2hwaW5zLG92ZXJhbGwsMTM4LDE3MiwwLjU3NTU4MTM5NTM0ODgzNzIsMC40MTIyMTM3NDA0NTgwMTUzLDAuNiwwLjMxMzk1MzQ4ODM3MjA5MywwLjQzNzYyODczNTQ4NzI3NzcKRElOT3YyIFJlZ2lvbi1Bd2FyZSBNZW1vcnksc2NyZXdfYmFnLGxvZ2ljYWwsMTIyLDEzNywwLjU0Mjk1Nzk5OTI4MjAzOSwwLjIzMzkxODEyODY1NDk3MDc1LDAuNTg4MjM1Mjk0MTE3NjQ3MSwwLjE0NTk4NTQwMTQ1OTg1NCwwLjYwNjY4MTUyNjYyNDIzOTUKRElOT3YyIFJlZ2lvbi1Bd2FyZSBNZW1vcnksc2NyZXdfYmFnLHN0cnVjdHVyYWwsMTIyLDgyLDAuNzk4MDgwNzY3NjkyOTIyOCwwLjU0NTQ1NDU0NTQ1NDU0NTQsMC43MiwwLjQzOTAyNDM5MDI0MzkwMjQ0LDAuNjA2NjgxNTI2NjI0MjM5NQpESU5PdjIgUmVnaW9uLUF3YXJlIE1lbW9yeSxzY3Jld19iYWcsb3ZlcmFsbCwxMjIsMjE5LDAuNjM4NDgzNDE5NDE3NjIxMSwwLjM4NzU0MzI1MjU5NTE1NTcsMC44LDAuMjU1NzA3NzYyNTU3MDc3NiwwLjYwNjY4MTUyNjYyNDIzOTUKRElOT3YyIFJlZ2lvbi1Bd2FyZSBNZW1vcnksc3BsaWNpbmdfY29ubmVjdG9ycyxsb2dpY2FsLDExOSwxMDgsMC43OTU5MDcyNTE3ODk2MDQ4LDAuNjc3MjQ4Njc3MjQ4Njc3MiwwLjc5MDEyMzQ1Njc5MDEyMzQsMC41OTI1OTI1OTI1OTI1OTI2LDAuNDQzMzk4NzA5NDgwNTc5MQpESU5PdjIgUmVnaW9uLUF3YXJlIE1lbW9yeSxzcGxpY2luZ19jb25uZWN0b3JzLHN0cnVjdHVyYWwsMTE5LDg1LDAuNzI1OTUxNTU3MDkzNDI1NiwwLjYxMjI0NDg5Nzk1OTE4MzcsMC43MjU4MDY0NTE2MTI5MDMyLDAuNTI5NDExNzY0NzA1ODgyNCwwLjQ0MzM5ODcwOTQ4MDU3OTEKRElOT3YyIFJlZ2lvbi1Bd2FyZSBNZW1vcnksc3BsaWNpbmdfY29ubmVjdG9ycyxvdmVyYWxsLDExOSwxOTMsMC43NjUwOTc3NDg5NDQxMzczLDAuNjgzMzg1NTc5OTM3MzA0MSwwLjg2NTA3OTM2NTA3OTM2NTEsMC41NjQ3NjY4MzkzNzgyMzg0LDAuNDQzMzk4NzA5NDgwNTc5MQpESU5PdjIgQ29tcG9zaXRpb24gSGlzdG9ncmFtIChCb1ZXKSxicmVha2Zhc3RfYm94LGxvZ2ljYWwsMTAyLDgzLDAuODA5OTQ1NjY1MDEyOTkzMywwLjc3MDI3MDI3MDI3MDI3MDMsMC44NzY5MjMwNzY5MjMwNzY5LDAuNjg2NzQ2OTg3OTUxODA3Miw2LjQxNzY5ODUzMjI1ODcyOApESU5PdjIgQ29tcG9zaXRpb24gSGlzdG9ncmFtIChCb1ZXKSxicmVha2Zhc3RfYm94LHN0cnVjdHVyYWwsMTAyLDkwLDAuNTIzODU2MjA5MTUwMzI2OCwwLjM5MzQ0MjYyMjk1MDgxOTY2LDAuNzUsMC4yNjY2NjY2NjY2NjY2NjY2Niw2LjQxNzY5ODUzMjI1ODcyOApESU5PdjIgQ29tcG9zaXRpb24gSGlzdG9ncmFtIChCb1ZXKSxicmVha2Zhc3RfYm94LG92ZXJhbGwsMTAyLDE3MywwLjY2MTExMzAwMDExMzM0MDEsMC42MTgzMjA2MTA2ODcwMjI5LDAuOTEwMTEyMzU5NTUwNTYxOCwwLjQ2ODIwODA5MjQ4NTU0OTEsNi40MTc2OTg1MzIyNTg3MjgKRElOT3YyIENvbXBvc2l0aW9uIEhpc3RvZ3JhbSAoQm9WVyksanVpY2VfYm90dGxlLGxvZ2ljYWwsOTQsMTQyLDAuNjA4MzMwODM2MDgwMzExOCwwLjUwNzMxNzA3MzE3MDczMTcsMC44MjUzOTY4MjUzOTY4MjU0LDAuMzY2MTk3MTgzMDk4NTkxNTYsNi4xNzU0NzA2MDc5OTI1NTcKRElOT3YyIENvbXBvc2l0aW9uIEhpc3RvZ3JhbSAoQm9WVyksanVpY2VfYm90dGxlLHN0cnVjdHVyYWwsOTQsOTQsMC40MDA0MDc0MjQxNzM4MzQzNSwwLjE0MTU5MjkyMDM1Mzk4MjMsMC40MjEwNTI2MzE1Nzg5NDczNSwwLjA4NTEwNjM4Mjk3ODcyMzQsNi4xNzU0NzA2MDc5OTI1NTcKRElOT3YyIENvbXBvc2l0aW9uIEhpc3RvZ3JhbSAoQm9WVyksanVpY2VfYm90dGxlLG92ZXJhbGwsOTQsMjM2LDAuNTI1NTEzODgzODgwMjc0MSwwLjM5MDg3OTQ3ODgyNzM2MTU3LDAuODQ1MDcwNDIyNTM1MjExMywwLjI1NDIzNzI4ODEzNTU5MzIsNi4xNzU0NzA2MDc5OTI1NTcKRElOT3YyIENvbXBvc2l0aW9uIEhpc3RvZ3JhbSAoQm9WVykscHVzaHBpbnMsbG9naWNhbCwxMzgsOTEsMC42NDY0NDA1MTYwMDU3MzM0LDAuNDY1NzUzNDI0NjU3NTM0MiwwLjYxODE4MTgxODE4MTgxODIsMC4zNzM2MjYzNzM2MjYzNzM2Myw1LjM0MzgzMDA0NTc2ODgxMwpESU5PdjIgQ29tcG9zaXRpb24gSGlzdG9ncmFtIChCb1ZXKSxwdXNocGlucyxzdHJ1Y3R1cmFsLDEzOCw4MSwwLjQ0NzEyODI4NzcwNzk5Nzg0LDAuMTExMTExMTExMTExMTExMSwwLjIyMjIyMjIyMjIyMjIyMjIsMC4wNzQwNzQwNzQwNzQwNzQwNyw1LjM0MzgzMDA0NTc2ODgxMwpESU5PdjIgQ29tcG9zaXRpb24gSGlzdG9ncmFtIChCb1ZXKSxwdXNocGlucyxvdmVyYWxsLDEzOCwxNzIsMC41NTI1NzgzNjE5ODE3OTk4LDAuMzQzMzQ3NjM5NDg0OTc4NTQsMC42NTU3Mzc3MDQ5MTgwMzI3LDAuMjMyNTU4MTM5NTM0ODgzNzIsNS4zNDM4MzAwNDU3Njg4MTMKRElOT3YyIENvbXBvc2l0aW9uIEhpc3RvZ3JhbSAoQm9WVyksc2NyZXdfYmFnLGxvZ2ljYWwsMTIyLDEzNywwLjU3OTc1MzUwMDA1OTgzMDIsMC4zMTY5Mzk4OTA3MTAzODI1MywwLjYzMDQzNDc4MjYwODY5NTcsMC4yMTE2Nzg4MzIxMTY3ODgzLDYuMDU2NDI4MzgwMjY4MTUKRElOT3YyIENvbXBvc2l0aW9uIEhpc3RvZ3JhbSAoQm9WVyksc2NyZXdfYmFnLHN0cnVjdHVyYWwsMTIyLDgyLDAuNTYzNDI0NjMwMTQ3OTQwOSwwLjIxNjIxNjIxNjIxNjIxNjIzLDAuNDEzNzkzMTAzNDQ4Mjc1ODYsMC4xNDYzNDE0NjM0MTQ2MzQxNCw2LjA1NjQyODM4MDI2ODE1CkRJTk92MiBDb21wb3NpdGlvbiBIaXN0b2dyYW0gKEJvVlcpLHNjcmV3X2JhZyxvdmVyYWxsLDEyMiwyMTksMC41NzM2Mzk0OTM5NzQwOTk5LDAuMjk2MDI4ODgwODY2NDI2LDAuNzA2ODk2NTUxNzI0MTM3OSwwLjE4NzIxNDYxMTg3MjE0NjEsNi4wNTY0MjgzODAyNjgxNQpESU5PdjIgQ29tcG9zaXRpb24gSGlzdG9ncmFtIChCb1ZXKSxzcGxpY2luZ19jb25uZWN0b3JzLGxvZ2ljYWwsMTE5LDEwOCwwLjU3MzM3Mzc5Mzk2MjAyOTEsMC4zNzI0MTM3OTMxMDM0NDgzLDAuNzI5NzI5NzI5NzI5NzI5NywwLjI1LDUuOTIzNzY0ODU2MjU0MzA4CkRJTk92MiBDb21wb3NpdGlvbiBIaXN0b2dyYW0gKEJvVlcpLHNwbGljaW5nX2Nvbm5lY3RvcnMsc3RydWN0dXJhbCwxMTksODUsMC41NTU5MDcwNjg3MDk4MzY5LDAuMjQwNzQwNzQwNzQwNzQwNzMsMC41NjUyMTczOTEzMDQzNDc4LDAuMTUyOTQxMTc2NDcwNTg4MjUsNS45MjM3NjQ4NTYyNTQzMDgKRElOT3YyIENvbXBvc2l0aW9uIEhpc3RvZ3JhbSAoQm9WVyksc3BsaWNpbmdfY29ubmVjdG9ycyxvdmVyYWxsLDExOSwxOTMsMC41NjU2ODExOTQ3NTc2OTU4LDAuMzI5MjE4MTA2OTk1ODg0OCwwLjgsMC4yMDcyNTM4ODYwMTAzNjI2OCw1LjkyMzc2NDg1NjI1NDMwOApGdXNpb24gKG1lYW4pLGJyZWFrZmFzdF9ib3gsbG9naWNhbCwxMDIsODMsMC45MDYwOTQ5NjgxMDc3MjQ5LDAuODIxMTkyMDUyOTgwMTMyNCwwLjkxMTc2NDcwNTg4MjM1MjksMC43NDY5ODc5NTE4MDcyMjg5LDEuMTIzOTkyODgzNjY0MDU4CkZ1c2lvbiAobWVhbiksYnJlYWtmYXN0X2JveCxzdHJ1Y3R1cmFsLDEwMiw5MCwwLjczOTg2OTI4MTA0NTc1MTYsMC41NjcxNjQxNzkxMDQ0Nzc2LDAuODYzNjM2MzYzNjM2MzYzNiwwLjQyMjIyMjIyMjIyMjIyMjIsMS4xMjM5OTI4ODM2NjQwNTgKRnVzaW9uIChtZWFuKSxicmVha2Zhc3RfYm94LG92ZXJhbGwsMTAyLDE3MywwLjgxOTYxOTE3NzE1MDYyODksMC43MTY4NDU4NzgxMzYyMDA3LDAuOTQzMzk2MjI2NDE1MDk0NCwwLjU3ODAzNDY4MjA4MDkyNDksMS4xMjM5OTI4ODM2NjQwNTgKRnVzaW9uIChtZWFuKSxqdWljZV9ib3R0bGUsbG9naWNhbCw5NCwxNDIsMC44NDcwOTMxOTc0ODI3Njg5LDAuNzc5MTE2NDY1ODYzNDUzOCwwLjkwNjU0MjA1NjA3NDc2NjMsMC42ODMwOTg1OTE1NDkyOTU4LC0wLjUxNDYwMjU3MjU0MDUxNDkKRnVzaW9uIChtZWFuKSxqdWljZV9ib3R0bGUsc3RydWN0dXJhbCw5NCw5NCwwLjgyOTIyMTM2NzEzNDQ1LDAuNjQ5MzUwNjQ5MzUwNjQ5MywwLjgzMzMzMzMzMzMzMzMzMzQsMC41MzE5MTQ4OTM2MTcwMjEzLC0wLjUxNDYwMjU3MjU0MDUxNDkKRnVzaW9uIChtZWFuKSxqdWljZV9ib3R0bGUsb3ZlcmFsbCw5NCwyMzYsMC44Mzk5NzQ3NTY1ODEzMTk5LDAuNzQ4MDkxNjAzMDUzNDM1MSwwLjkzNjMwNTczMjQ4NDA3NjQsMC42MjI4ODEzNTU5MzIyMDM0LC0wLjUxNDYwMjU3MjU0MDUxNDkKRnVzaW9uIChtZWFuKSxwdXNocGlucyxsb2dpY2FsLDEzOCw5MSwwLjU5OTc3NzAzNDU1OTY0MzQsMC41NzM1ODQ5MDU2NjAzNzczLDAuNDM2NzgxNjA5MTk1NDAyMywwLjgzNTE2NDgzNTE2NDgzNTIsMC4wNzQxMzA5MjQwMjg1NzkwMQpGdXNpb24gKG1lYW4pLHB1c2hwaW5zLHN0cnVjdHVyYWwsMTM4LDgxLDAuOTgzMDkxNzg3NDM5NjEzNSwwLjYyMzA3NjkyMzA3NjkyMzEsMC40NTI1MTM5NjY0ODA0NDY5NSwxLjAsMC4wNzQxMzA5MjQwMjg1NzkwMQpGdXNpb24gKG1lYW4pLHB1c2hwaW5zLG92ZXJhbGwsMTM4LDE3MiwwLjc4MDI5MTU0MDI3NjM3MzQsMC43MzUzNjI5OTc2NTgwNzk3LDAuNjE1Njg2Mjc0NTA5ODA0LDAuOTEyNzkwNjk3Njc0NDE4NiwwLjA3NDEzMDkyNDAyODU3OTAxCkZ1c2lvbiAobWVhbiksc2NyZXdfYmFnLGxvZ2ljYWwsMTIyLDEzNywwLjYyNzU1NzczNjAyOTY3NTgsMC4yNjM0NzMwNTM4OTIyMTU2LDAuNzMzMzMzMzMzMzMzMzMzMywwLjE2MDU4Mzk0MTYwNTgzOTQxLDEuMzE2NDIzMzYyMDM4NTcyMQpGdXNpb24gKG1lYW4pLHNjcmV3X2JhZyxzdHJ1Y3R1cmFsLDEyMiw4MiwwLjc5ODA4MDc2NzY5MjkyMjksMC41MjQ1OTAxNjM5MzQ0MjYzLDAuOCwwLjM5MDI0MzkwMjQzOTAyNDQsMS4zMTY0MjMzNjIwMzg1NzIxCkZ1c2lvbiAobWVhbiksc2NyZXdfYmFnLG92ZXJhbGwsMTIyLDIxOSwwLjY5MTQwNjU0MjQwNTg2ODYsMC4zODQzNDE2MzcwMTA2NzYxNCwwLjg3MDk2Nzc0MTkzNTQ4MzksMC4yNDY1NzUzNDI0NjU3NTM0LDEuMzE2NDIzMzYyMDM4NTcyMQpGdXNpb24gKG1lYW4pLHNwbGljaW5nX2Nvbm5lY3RvcnMsbG9naWNhbCwxMTksMTA4LDAuNjc2MzE0OTcwNDMyNjE3NSwwLjUyNDM5MDI0MzkwMjQzOSwwLjc2Nzg1NzE0Mjg1NzE0MjksMC4zOTgxNDgxNDgxNDgxNDgxNCwwLjI4Nzc1MzI5NTAxNzYwOTYKRnVzaW9uIChtZWFuKSxzcGxpY2luZ19jb25uZWN0b3JzLHN0cnVjdHVyYWwsMTE5LDg1LDAuNjY4OTA3NTYzMDI1MjEwMiwwLjUxNTE1MTUxNTE1MTUxNTEsMC43MjM0MDQyNTUzMTkxNDksMC40LDAuMjg3NzUzMjk1MDE3NjA5NgpGdXNpb24gKG1lYW4pLHNwbGljaW5nX2Nvbm5lY3RvcnMsb3ZlcmFsbCwxMTksMTkzLDAuNjczMDUyNjQwNzQ1NDE3MiwwLjU0NDE2OTYxMTMwNzQyMDUsMC44NTU1NTU1NTU1NTU1NTU1LDAuMzk4OTYzNzMwNTY5OTQ4MTYsMC4yODc3NTMyOTUwMTc2MDk2CkZ1c2lvbiAobWF4KSxicmVha2Zhc3RfYm94LGxvZ2ljYWwsMTAyLDgzLDAuODk5MDA3Nzk1ODg5NDQwMSwwLjgyMTkxNzgwODIxOTE3OCwwLjk1MjM4MDk1MjM4MDk1MjMsMC43MjI4OTE1NjYyNjUwNjAyLDIuNDAwNDMzMzM4NDczMzkwNwpGdXNpb24gKG1heCksYnJlYWtmYXN0X2JveCxzdHJ1Y3R1cmFsLDEwMiw5MCwwLjc3OTE5Mzg5OTc4MjEzNSwwLjU0Njg3NSwwLjkyMTA1MjYzMTU3ODk0NzMsMC4zODg4ODg4ODg4ODg4ODg5LDIuNDAwNDMzMzM4NDczMzkwNwpGdXNpb24gKG1heCksYnJlYWtmYXN0X2JveCxvdmVyYWxsLDEwMiwxNzMsMC44MzY2NzY4NjcyNzg3MDMzLDAuNzAxMTA3MDExMDcwMTEwOCwwLjk2OTM4Nzc1NTEwMjA0MDgsMC41NDkxMzI5NDc5NzY4Nzg2LDIuNDAwNDMzMzM4NDczMzkwNwpGdXNpb24gKG1heCksanVpY2VfYm90dGxlLGxvZ2ljYWwsOTQsMTQyLDAuNzMzODE3ODAwNDE5NTM4NiwwLjY1Nzg5NDczNjg0MjEwNTMsMC44NzIwOTMwMjMyNTU4MTQsMC41MjgxNjkwMTQwODQ1MDcsMS4zMDc4NzYyNjQ0MzgwOTU1CkZ1c2lvbiAobWF4KSxqdWljZV9ib3R0bGUsc3RydWN0dXJhbCw5NCw5NCwwLjUwODE0ODQ4MzQ3NjY4NjMsMC4yMzUyOTQxMTc2NDcwNTg4MiwwLjU2LDAuMTQ4OTM2MTcwMjEyNzY1OTUsMS4zMDc4NzYyNjQ0MzgwOTU1CkZ1c2lvbiAobWF4KSxqdWljZV9ib3R0bGUsb3ZlcmFsbCw5NCwyMzYsMC42NDM5MzI1NjQwMTAwOTcyLDAuNTI5NzYxOTA0NzYxOTA0OCwwLjg5LDAuMzc3MTE4NjQ0MDY3Nzk2NiwxLjMwNzg3NjI2NDQzODA5NTUKRnVzaW9uIChtYXgpLHB1c2hwaW5zLGxvZ2ljYWwsMTM4LDkxLDAuNTY0NTAwNzE2Njc0NjI5OSwwLjYxMDI5NDExNzY0NzA1ODksMC40NTg1NjM1MzU5MTE2MDIyLDAuOTEyMDg3OTEyMDg3OTEyMSwxLjI5MDQzMzcwODMxNTIwODYKRnVzaW9uIChtYXgpLHB1c2hwaW5zLHN0cnVjdHVyYWwsMTM4LDgxLDAuOTg5MjY0NjI2OTQ1Nzg2MywwLjYyMzA3NjkyMzA3NjkyMzEsMC40NTI1MTM5NjY0ODA0NDY5NSwxLjAsMS4yOTA0MzM3MDgzMTUyMDg2CkZ1c2lvbiAobWF4KSxwdXNocGlucyxvdmVyYWxsLDEzOCwxNzIsMC43NjQ1MzQ4ODM3MjA5MzAxLDAuNzU1NzYwMzY4NjYzNTk0NCwwLjYyNTk1NDE5ODQ3MzI4MjUsMC45NTM0ODgzNzIwOTMwMjMzLDEuMjkwNDMzNzA4MzE1MjA4NgpGdXNpb24gKG1heCksc2NyZXdfYmFnLGxvZ2ljYWwsMTIyLDEzNywwLjU2OTI4MzIzNTYxMDg2NTIsMC4yNzIxODkzNDkxMTI0MjYwNCwwLjcxODc1LDAuMTY3ODgzMjExNjc4ODMyMSwyLjIyMzU2MTg4ODA3OTM5MTUKRnVzaW9uIChtYXgpLHNjcmV3X2JhZyxzdHJ1Y3R1cmFsLDEyMiw4MiwwLjc1ODM5NjY0MTM0MzQ2MjYsMC41MDgxOTY3MjEzMTE0NzU0LDAuNzc1LDAuMzc4MDQ4NzgwNDg3ODA0OSwyLjIyMzU2MTg4ODA3OTM5MTUKRnVzaW9uIChtYXgpLHNjcmV3X2JhZyxvdmVyYWxsLDEyMiwyMTksMC42NDAwOTI4MjEzMTg5NjEsMC4zODI5Nzg3MjM0MDQyNTUzLDAuODU3MTQyODU3MTQyODU3MSwwLjI0NjU3NTM0MjQ2NTc1MzQsMi4yMjM1NjE4ODgwNzkzOTE1CkZ1c2lvbiAobWF4KSxzcGxpY2luZ19jb25uZWN0b3JzLGxvZ2ljYWwsMTE5LDEwOCwwLjY5MjExMDE3NzQwNDI5NSwwLjQ0NTk0NTk0NTk0NTk0NTk0LDAuODI1LDAuMzA1NTU1NTU1NTU1NTU1NiwxLjU1MzgzMTgwMzEyOTg1MTcKRnVzaW9uIChtYXgpLHNwbGljaW5nX2Nvbm5lY3RvcnMsc3RydWN0dXJhbCwxMTksODUsMC42NzIwNzExODE0MTM3NDE5LDAuMjgwMzczODMxNzc1NzAwOSwwLjY4MTgxODE4MTgxODE4MTgsMC4xNzY0NzA1ODgyMzUyOTQxMywxLjU1MzgzMTgwMzEyOTg1MTcKRnVzaW9uIChtYXgpLHNwbGljaW5nX2Nvbm5lY3RvcnMsb3ZlcmFsbCwxMTksMTkzLDAuNjgzMjg0NzEyODQ4ODcsMC4zODcwOTY3NzQxOTM1NDg0LDAuODcyNzI3MjcyNzI3MjcyNywwLjI0ODcwNDY2MzIxMjQzNTIzLDEuNTUzODMxODAzMTI5ODUxNwpGdXNpb24gKHJhbmstYXZnKSxicmVha2Zhc3RfYm94LGxvZ2ljYWwsMTAyLDgzLDAuODgxMTcxNzQ1ODA2NzU2NCwwLjcxOTQyNDQ2MDQzMTY1NDYsMC44OTI4NTcxNDI4NTcxNDI5LDAuNjAyNDA5NjM4NTU0MjE2OSwwLjc2NDg0NzgzNzY5MzUzOTcKRnVzaW9uIChyYW5rLWF2ZyksYnJlYWtmYXN0X2JveCxzdHJ1Y3R1cmFsLDEwMiw5MCwwLjczNDk2NzMyMDI2MTQzNzksMC41MjMwNzY5MjMwNzY5MjMxLDAuODUsMC4zNzc3Nzc3Nzc3Nzc3Nzc3NywwLjc2NDg0NzgzNzY5MzUzOTcKRnVzaW9uIChyYW5rLWF2ZyksYnJlYWtmYXN0X2JveCxvdmVyYWxsLDEwMiwxNzMsMC44MDUxMTE2NDAwMzE3MzUzLDAuNjM4NzgzMjY5OTYxOTc3MiwwLjkzMzMzMzMzMzMzMzMzMzMsMC40ODU1NDkxMzI5NDc5NzY4NiwwLjc2NDg0NzgzNzY5MzUzOTcKRnVzaW9uIChyYW5rLWF2ZyksanVpY2VfYm90dGxlLGxvZ2ljYWwsOTQsMTQyLDAuODE1NDc3OTc0MjI4MzQ4OSwwLjc1NTAyMDA4MDMyMTI4NTEsMC44Nzg1MDQ2NzI4OTcxOTYyLDAuNjYxOTcxODMwOTg1OTE1NSwwLjMwMzY2MjU3MzQxMTYzOTE2CkZ1c2lvbiAocmFuay1hdmcpLGp1aWNlX2JvdHRsZSxzdHJ1Y3R1cmFsLDk0LDk0LDAuNzM4NjgyNjYxODM3OTM1NywwLjUyNDEzNzkzMTAzNDQ4MjgsMC43NDUwOTgwMzkyMTU2ODYzLDAuNDA0MjU1MzE5MTQ4OTM2MTQsMC4zMDM2NjI1NzM0MTE2MzkxNgpGdXNpb24gKHJhbmstYXZnKSxqdWljZV9ib3R0bGUsb3ZlcmFsbCw5NCwyMzYsMC43ODQ4OTAwMTA4MTg2MDgxLDAuNjkyOTEzMzg1ODI2NzcxNiwwLjkxMDM0NDgyNzU4NjIwNjksMC41NTkzMjIwMzM4OTgzMDUsMC4zMDM2NjI1NzM0MTE2MzkxNgpGdXNpb24gKHJhbmstYXZnKSxwdXNocGlucyxsb2dpY2FsLDEzOCw5MSwwLjYxMDIwODYzMTk0Nzc2MjQsMC41LDAuNDU4NzE1NTk2MzMwMjc1MjUsMC41NDk0NTA1NDk0NTA1NDk1LDAuNDQ1MTg5NTM1NTA0NTM4MgpGdXNpb24gKHJhbmstYXZnKSxwdXNocGlucyxzdHJ1Y3R1cmFsLDEzOCw4MSwwLjY0NDEyMjM4MzI1MjgxOCwwLjU0MTY2NjY2NjY2NjY2NjYsMC40Njg0Njg0Njg0Njg0Njg0NiwwLjY0MTk3NTMwODY0MTk3NTMsMC40NDUxODk1MzU1MDQ1MzgyCkZ1c2lvbiAocmFuay1hdmcpLHB1c2hwaW5zLG92ZXJhbGwsMTM4LDE3MiwwLjYyNjE3OTY0MjczNjc3MTIsMC42MTI2MTI2MTI2MTI2MTI2LDAuNjMzNTQwMzcyNjcwODA3NCwwLjU5MzAyMzI1NTgxMzk1MzUsMC40NDUxODk1MzU1MDQ1MzgyCkZ1c2lvbiAocmFuay1hdmcpLHNjcmV3X2JhZyxsb2dpY2FsLDEyMiwxMzcsMC42Mjg0ODUxMDIzMDk0NDExLDAuMjcwNTg4MjM1Mjk0MTE3NjMsMC42OTY5Njk2OTY5Njk2OTcsMC4xNjc4ODMyMTE2Nzg4MzIxLDAuNzgwNDkxMTkwNjAzMzEwMgpGdXNpb24gKHJhbmstYXZnKSxzY3Jld19iYWcsc3RydWN0dXJhbCwxMjIsODIsMC43OTQ1ODIxNjcxMzMxNDY3LDAuNDQwNjc3OTY2MTAxNjk0OSwwLjcyMjIyMjIyMjIyMjIyMjIsMC4zMTcwNzMxNzA3MzE3MDczLDAuNzgwNDkxMTkwNjAzMzEwMgpGdXNpb24gKHJhbmstYXZnKSxzY3Jld19iYWcsb3ZlcmFsbCwxMjIsMjE5LDAuNjkwNjc2Njk3MzU3NTg2NiwwLjM1MjUxNzk4NTYxMTUxMDc2LDAuODMwNTA4NDc0NTc2MjcxMiwwLjIyMzc0NDI5MjIzNzQ0MjksMC43ODA0OTExOTA2MDMzMTAyCkZ1c2lvbiAocmFuay1hdmcpLHNwbGljaW5nX2Nvbm5lY3RvcnMsbG9naWNhbCwxMTksMTA4LDAuNjk5MTEyOTc4NTI0NzQzMywwLjU0NDM3ODY5ODIyNDg1MjEsMC43NTQwOTgzNjA2NTU3Mzc3LDAuNDI1OTI1OTI1OTI1OTI1OTMsMC40OTg2NDM4ODY4MTI2MDAxCkZ1c2lvbiAocmFuay1hdmcpLHNwbGljaW5nX2Nvbm5lY3RvcnMsc3RydWN0dXJhbCwxMTksODUsMC42ODYzMDc0NjQxNjIxMzU1LDAuNTQwMTQ1OTg1NDAxNDU5OSwwLjcxMTUzODQ2MTUzODQ2MTYsMC40MzUyOTQxMTc2NDcwNTg4MywwLjQ5ODY0Mzg4NjgxMjYwMDEKRnVzaW9uIChyYW5rLWF2Zyksc3BsaWNpbmdfY29ubmVjdG9ycyxvdmVyYWxsLDExOSwxOTMsMC42OTM0NzMyNDQyMTk5Njc4LDAuNTcwNDQ2NzM1Mzk1MTg5LDAuODQ2OTM4Nzc1NTEwMjA0MSwwLjQzMDA1MTgxMzQ3MTUwMjU2LDAuNDk4NjQzODg2ODEyNjAwMQo=", BinaryEncoding.Base64), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"method", type text}, {"category", type text}, {"anomaly_type", type text}, {"n_good", Int64.Type}, {"n_anomaly", Int64.Type}, {"auroc", type number}, {"f1", type number}, {"precision", type number}, {"recall", type number}, {"val_threshold", type number}})
				in
				    Typed

	annotation PBI_ResultType = Table

