table 'Feature Variants'
	lineageTag: c6c31c61-7ebc-5632-bf19-c00b2ef4257f

	column model
		dataType: string
		lineageTag: 8eaf10f4-fb74-5659-a890-8cf9d8a41be2
		summarizeBy: none
		sourceColumn: model

		annotation SummarizationSetBy = User

	column n_branches
		dataType: int64
		formatString: 0
		lineageTag: a8f750a2-7385-5faa-8a76-76cd53a22e51
		summarizeBy: none
		sourceColumn: n_branches

		annotation SummarizationSetBy = User

	column branches
		dataType: string
		lineageTag: 4d2c9fdc-3626-5008-b036-4c2e7e5e9014
		summarizeBy: none
		sourceColumn: branches

		annotation SummarizationSetBy = User

	column logical
		dataType: double
		formatString: 0.000
		lineageTag: bb721a5a-d089-5740-829a-1376ac4aac62
		summarizeBy: none
		sourceColumn: logical

		annotation SummarizationSetBy = User

	column structural
		dataType: double
		formatString: 0.000
		lineageTag: ab4e5a46-004f-5878-a317-2f1b09510e7c
		summarizeBy: none
		sourceColumn: structural

		annotation SummarizationSetBy = User

	column overall
		dataType: double
		formatString: 0.000
		lineageTag: 44eab203-bb50-5d18-99c0-121df8abcd4c
		summarizeBy: none
		sourceColumn: overall

		annotation SummarizationSetBy = User

	partition 'Feature Variants-Embedded' = m
		mode: import
		source =
				let
				    Source = Csv.Document(Binary.FromText("bW9kZWwsbl9icmFuY2hlcyxicmFuY2hlcyxsb2dpY2FsLHN0cnVjdHVyYWwsb3ZlcmFsbAoiQWxsIGZlYXR1cmVzICg1LCBpbmNsLiBkdXBsaWNhdGUpIiw1LEdsb2JhbCBJbWFnZS1TdGF0IChwcm94eSkgKyBESU5PdjIgUGF0Y2ggTWVtb3J5ICsgRElOT3YyIFBhdGNoTWVtb3J5IChkdXApICsgRElOT3YyIFJlZ2lvbi1Bd2FyZSArIERJTk92MiBDb21wb3NpdGlvbiBIaXN0LDAuNzMxNCwwLjgwMzgsMC43NjA5CkRyb3AgcmVkdW5kYW50IGR1cGxpY2F0ZSAoNCB1bmlxdWUpLDQsR2xvYmFsIEltYWdlLVN0YXQgKHByb3h5KSArIERJTk92MiBQYXRjaCBNZW1vcnkgKyBESU5PdjIgUmVnaW9uLUF3YXJlICsgRElOT3YyIENvbXBvc2l0aW9uIEhpc3QsMC43MjU0LDAuNzc5NywwLjc0NzIKRmVhdHVyZS1zZWxlY3RlZCAoMzogZHJvcCByZWR1bmRhbnQgKyBoYXJtZnVsKSwzLEdsb2JhbCBJbWFnZS1TdGF0IChwcm94eSkgKyBESU5PdjIgUGF0Y2ggTWVtb3J5ICsgRElOT3YyIFJlZ2lvbi1Bd2FyZSwwLjcxODEsMC44MjYxLDAuNzYzOApTdHJvbmcgRElOT3YyIG1lbW9yaWVzIG9ubHkgKDIpLDIsRElOT3YyIFBhdGNoIE1lbW9yeSArIERJTk92MiBSZWdpb24tQXdhcmUsMC43MTc5LDAuNzc4NiwwLjc0MTMKQmVzdCBzaW5nbGUgcmVwcmVzZW50YXRpb24sMSxESU5PdjIgUmVnaW9uLUF3YXJlLDAuNzMwMSwwLjc4MzYsMC43NTAzCg==", BinaryEncoding.Base64), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"model", type text}, {"n_branches", Int64.Type}, {"branches", type text}, {"logical", type number}, {"structural", type number}, {"overall", type number}})
				in
				    Typed

	annotation PBI_ResultType = Table

