table 'Main Results'
	lineageTag: e1bd2bed-6d20-597b-8bb5-57059de485f5

	column method
		dataType: string
		lineageTag: 4a5c355e-f1be-501f-82bf-4de0ccb3ff23
		summarizeBy: none
		sourceColumn: method

		annotation SummarizationSetBy = User

	column logical
		dataType: double
		formatString: 0.000
		lineageTag: b1f9a5e9-ba0f-5f45-bad5-9dd603473a55
		summarizeBy: none
		sourceColumn: logical

		annotation SummarizationSetBy = User

	column overall
		dataType: double
		formatString: 0.000
		lineageTag: ae4382ff-fc95-5fb5-a31e-f05d43f37b56
		summarizeBy: none
		sourceColumn: overall

		annotation SummarizationSetBy = User

	column structural
		dataType: double
		formatString: 0.000
		lineageTag: 2cb62d32-99ea-5846-a4e3-6521d66fc1e0
		summarizeBy: none
		sourceColumn: structural

		annotation SummarizationSetBy = User

	column mean_logical_structural
		dataType: double
		formatString: 0.000
		lineageTag: 3d74891d-1250-58db-966c-51775f5a965e
		summarizeBy: none
		sourceColumn: mean_logical_structural

		annotation SummarizationSetBy = User

	column f1_logical
		dataType: double
		formatString: 0.000
		lineageTag: d584fe31-0472-5afa-9eff-74ec4dbf9c5e
		summarizeBy: none
		sourceColumn: f1_logical

		annotation SummarizationSetBy = User

	column f1_overall
		dataType: double
		formatString: 0.000
		lineageTag: efa8397a-c503-592e-afdf-a40c57d0675c
		summarizeBy: none
		sourceColumn: f1_overall

		annotation SummarizationSetBy = User

	column f1_structural
		dataType: double
		formatString: 0.000
		lineageTag: 1947c0b2-e8bf-5689-ab04-680b20051ce1
		summarizeBy: none
		sourceColumn: f1_structural

		annotation SummarizationSetBy = User

	partition 'Main Results-Embedded' = m
		mode: import
		source =
				let
				    Source = Csv.Document(Binary.FromText("bWV0aG9kLGxvZ2ljYWwsb3ZlcmFsbCxzdHJ1Y3R1cmFsLG1lYW5fbG9naWNhbF9zdHJ1Y3R1cmFsLGYxX2xvZ2ljYWwsZjFfb3ZlcmFsbCxmMV9zdHJ1Y3R1cmFsCkZ1c2lvbiAobWVhbiksMC43MzEzNjc1ODEzMjI0ODYsMC43NjA4Njg5MzE0MzE5MjE2LDAuODAzODM0MTUzMjY3NTg5NywwLjc2NzYwMDg2NzI5NTAzNzgsMC41OTIzNTEzNDQ0NTk3MjM3LDAuNjI1NzYyMzQ1NDMzMTYyNCwwLjU3NTg2NjY4NjEyMzU5ODMKRElOT3YyIFJlZ2lvbi1Bd2FyZSBNZW1vcnksMC43MzAwODY4NTU3OTM3Nzg3LDAuNzUwMjg0OTUyOTg2MjYxOSwwLjc4MzU4NDYzNzIwNTg1ODEsMC43NTY4MzU3NDY0OTk4MTg0LDAuNTYyNTg4MTg1MTAxMjMwOCwwLjYyNTkyNDg4MTk0NzU1OTcsMC42MzkyNzU0ODI5MjA0NDA5CkRJTk92MiBQYXRjaCBNZW1vcnkgKE5OKSwwLjY5NzQ5MjM5MjA2MjM2MzgsMC43MjQ0MDAzODM3NzE1MzMzLDAuNzY1MTc4OTE1ODE5ODU2MSwwLjczMTMzNTY1Mzk0MTExLDAuNTQ4MDYxNjE2Njc1MzQxLDAuNjExNzEzNjExODU3MDAxNywwLjYxMTkyOTA4NTkzMzk0NTgKRnVzaW9uIChyYW5rLWF2ZyksMC43MjY4OTEyODY1NjM0MTA0LDAuNzIwMDY2MjQ3MDMyOTMzOCwwLjcxOTczMjM5OTMyOTQ5NDcsMC43MjMzMTE4NDI5NDY0NTI2LDAuNTU3ODgyMjk0ODU0MzgxOCwwLjU3MzQ1NDc5Nzg4MTYxMjIsMC41MTM5NDEwOTQ0NTYyNDU1CkZ1c2lvbiAobWF4KSwwLjY5MTc0Mzk0NTE5OTc1MzgsMC43MTM3MDQzNjk4MzU1MTIzLDAuNzQxNDE0OTY2NTkyMzYyNCwwLjcxNjU3OTQ1NTg5NjA1ODEsMC41NjE2NDgzOTE1NTMzNDI4LDAuNTUxMzQwOTU2NDE4NjgyNywwLjQzODc2MzMxODc2MjIzMTcKR2xvYmFsIEltYWdlLVN0YXQgRGV0ZWN0b3IgKHByb3h5KSwwLjYzNDEyODA4NjM3MTI1OSwwLjY1NDg0MDE3Nzk2NDc3NjMsMC42ODMyNDgzMjI1OTU0ODE1LDAuNjU4Njg4MjA0NDgzMzcwMiwwLjQ1NzI4ODE3MTkzOTc0NDQ3LDAuNDc0MDE3NTY2MjAyOTMyOCwwLjQwMzc3NDI1OTUxNDYyNDY0CkRJTk92MiBDb21wb3NpdGlvbiBIaXN0b2dyYW0gKEJvVlcpLDAuNjQzNTY4ODYyMjI0MTc5NSwwLjU3NTcwNTE4Njk0MTQ0MTksMC40OTgxNDQ3MjM5Nzc5ODczNywwLjU3MDg1Njc5MzEwMTA4MzUsMC40ODY1Mzg4OTAzODI0NzM0NCwwLjM5NTU1ODk0MzM3MjMzNDc3LDAuMjIwNjIwNzIyMjc0NTc0MDIK", BinaryEncoding.Base64), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"method", type text}, {"logical", type number}, {"overall", type number}, {"structural", type number}, {"mean_logical_structural", type number}, {"f1_logical", type number}, {"f1_overall", type number}, {"f1_structural", type number}})
				in
				    Typed

	annotation PBI_ResultType = Table

